// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh9HvySQzrf3TuYZ0tDQ62Gj4f0LpDppQ',
    appId: '1:1016129227133:web:40eb62a20f92b600d56414',
    messagingSenderId: '1016129227133',
    projectId: 'e-commerce-app-66a54',
    authDomain: 'e-commerce-app-66a54.firebaseapp.com',
    storageBucket: 'e-commerce-app-66a54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0yoj5bMYCgZLKeiuzqXzjsUUExL3E-I',
    appId: '1:1016129227133:android:7be1fa759e4d6592d56414',
    messagingSenderId: '1016129227133',
    projectId: 'e-commerce-app-66a54',
    storageBucket: 'e-commerce-app-66a54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRSPtRVGNnenPFAA3MP5v-zTu9wJG2das',
    appId: '1:1016129227133:ios:9f1d0766ad9977c5d56414',
    messagingSenderId: '1016129227133',
    projectId: 'e-commerce-app-66a54',
    storageBucket: 'e-commerce-app-66a54.firebasestorage.app',
    iosBundleId: 'com.baniyaprasannata.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRSPtRVGNnenPFAA3MP5v-zTu9wJG2das',
    appId: '1:1016129227133:ios:9f1d0766ad9977c5d56414',
    messagingSenderId: '1016129227133',
    projectId: 'e-commerce-app-66a54',
    storageBucket: 'e-commerce-app-66a54.firebasestorage.app',
    iosBundleId: 'com.baniyaprasannata.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh9HvySQzrf3TuYZ0tDQ62Gj4f0LpDppQ',
    appId: '1:1016129227133:web:9bed455c5196fca8d56414',
    messagingSenderId: '1016129227133',
    projectId: 'e-commerce-app-66a54',
    authDomain: 'e-commerce-app-66a54.firebaseapp.com',
    storageBucket: 'e-commerce-app-66a54.firebasestorage.app',
  );
}
